### ISSUE TITLE
Menampilkan Grafik Data Sensor

### ISSUE THREAD

**Issue by w1lldone** [marcohartono/Project-AQI-sensor#10]

**Comment by michaelr1300** [comment]
Package yg digunakan: 
https://github.com/J-T-McC/vue3-chartjs

Documentation ChartJS
https://www.chartjs.org/docs/latest/


Contoh file nya sudah ada di branch `feature/chart` di halaman About
Bisa dicoba, jangan lupa `npm install` dulu

**Comment by marcohartono** [comment]
grafik sensor sudah berhasil ditampilkan
